### ISSUE TITLE
Why not use aria2 instead of wget?

### ISSUE THREAD

**Issue by ndyakov** [jweslley/youtube-dl-mp3#3]
aria2 will be able to make multiple requests so it shall be faster than wget in theory.
Why not use it ?

**Comment by jweslley** [comment]
I dont know aria2. in the other hand, wget is shipped in every linux distro.

**Comment by ndyakov** [comment]
That will be a good point if everything else was shipped with the distro, but it is not. Also the new version of youtube-dl has options  --extract-audio and --audio-format mp3. After all if you have time, take a look at aria2 or axel.

**Comment by ivansabik** [comment]
I prefer no additional dependencies, I would go with wget which is more common, aria2 is nice though
