### ISSUE TITLE
Why not use --extract-audio?

### ISSUE THREAD

**Issue by chankeypathak** [jweslley/youtube-dl-mp3#6]
This is so slow as compared to the native solution

<pre>youtube-dl --extract-audio --audio-format mp3 videoURL</pre>

**Comment by jweslley** [comment]
hi @chankeypathak  you're right. In fact, I dont use this script anymore. I have a [youtube-dl config file](https://github.com/jweslley/dotfiles/blob/master/etc/youtube-dl.conf) which sets `--audio-format mp3` by default and when I wanna download just audio I just type: `youtube-dl -x <url>`

**Comment by chankeypathak** [comment]
Ah OK.

Yes. Setting options in conf file is better.

**Comment by matteocontrini** [comment]
Why where you converting the video to wav and then to MP3 with lame? Wasn't ffmpeg with MP3 output enough?

Thanks.

**Comment by jweslley** [comment]
@matteocontrini Please just use the youtube-dl´s built-in solution to extract audio. It´s simpler. :D

**Comment by matteocontrini** [comment]
Just asked why...

**Comment by jweslley** [comment]
I wrote this a long long time ago I just can't remember...

**Comment by diveyez** [comment]
https://github.com/diveyez/y2mp3/
HOPE THAT HELPS!
