### ISSUE TITLE
Question: what kbps will the downloaded mp3 be?

### ISSUE THREAD

**Issue by thibmaek** [jweslley/youtube-dl-mp3#8]

**Comment by nhumblot** [comment]
By looking to the source code, it converts the mp3 to 320 kbps.

**Comment by jweslley** [comment]
Thanks by the response @nhumblot .

I could recommend to use just  youtube-dl which already allows extract audio. More details here:

[https://github.com/jweslley/youtube-dl-mp3/issues/6]()
