### ISSUE TITLE
Simplify to one line ?

### ISSUE THREAD

**Issue by rst0git** [jweslley/youtube-dl-mp3#9]
```
#!/bin/bash
youtube-dl --extract-audio --audio-format mp3 -f bestaudio --ignore-errors -o "%(title)s.%(ext)s" $@
```

**Comment by r00tn3p4l** [comment]
No requirements ?

**Comment by r00tn3p4l** [comment]
install the requirements, maybe you can apt-get install youtube-dl wget ffmpeg lame

**Comment by rst0git** [comment]
Only youtube-dl
`apt-get install youtube-dl`

**Comment by rst0git** [comment]
Or
`sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl`
`sudo chmod a+rx /usr/local/bin/youtube-dl`

**Comment by tiago4171** [comment]
I think with pip this is easier

```
sudo apt install python-pip
pip install youtube_dl
```

**Comment by Alaradia** [comment]
yeah i agree the pip method is way better with apt the version is out of date and the script doesnt work

**Comment by gitnepal** [comment]
yeah, pip and gem ruling the apt

**Comment by branb** [comment]
@rst0git Can you submit a pull request with your changes so @jweslley might update this repository?

**Comment by rst0git** [comment]
Hi @branb Thank you for the suggestion, I submit a PR #10
